baseURL = 'https://example.org/'
locale = 'fr-fr'
timeZone = 'Europe/Paris'
title = 'Plume'
theme = 'archie'
copyright = "© Val"
summaryLength = 10

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle ='''Bienvenue sur Plume !\
    Je m'appelle Val. Je suis ingénieur en télécom et développeur chez Enedis.\
    Tu peux en apprendre un peu plus sur moi sur [mon site](https://jossic.fr).\
    Sur ce site, tu retrouveras des [photos](/photos/), mon [recueil](/recueil/), des [lettres](/lettres/) et des détails sur mes [projets](/projets/).\
    \
    Bonne lecture :)
    '''
	customcss = ["css/first.css"]
    mainSections = ['lettres', 'recueil']

[pagination]
  pagerSize = 10 # articles per page

[[params.social]]
    name = "Website"
    icon = "globe"
    url = "https://jossic.fr"

[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/vqlion"

[[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    url = "https://fr.linkedin.com/in/vqlion/"

[[params.social]]
    name = "E-mail"
    icon = "mail"
    url = "mailto:bonjour[at]jossic.fr"

[[menu.main]]
name = 'Accueil'
url = '/'
weight = 10

[[menu.main]]
name = 'Photos'
url = '/photos/'
weight = 20

[[menu.main]]
name = 'Recueil'
url = '/recueil/'
weight = 30

[[menu.main]]
name = 'Lettres'
url = '/lettres/'
weight = 40

[[menu.main]]
name = 'Projets'
url = '/projets/'
weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
