baseURL = 'https://example.org/'
locale = 'fr-fr'
timeZone = 'Europe/Paris'
title = 'Plume'
theme = 'archie'
copyright = "© Val"


[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle ='''Bienvenue sur Plume !\
    Je m'appelle Val. Je suis ingénieur en télécom et développeur chez Enedis.\
    Sur ce site, tu retrouveras des [lettres](/lettres), des [articles de blog](/articles) et quelques détails sur mes [projets](/projets).\
    \
    Bonne lecture :)
    '''
	customcss = ["css/first.css"]
    favicon = "favicon.svg"
    mainSections = ['lettres', 'projets']

[pagination]
  pagerSize = 10 # articles per page

[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/vqlion"

[[params.social]]
    name = "Website"
    icon = "globe"
    url = "https://jossic.fr"

[[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    url = "https://fr.linkedin.com/in/vqlion/"

[[params.social]]
    name = "E-mail"
    icon = "mail"
    url = "mailto:bonjour[at]jossic.fr"

[[menu.main]]
name = 'Accueil'
url = '/'
weight = 10

[[menu.main]]
name = 'Lettres'
url = '/lettres'
weight = 11

[[menu.main]]
name = 'Articles'
url = '/articles'
weight = 12

[[menu.main]]
name = 'Projets'
url = '/projets'
weight = 13

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
